airscripts/awesome-steam-deck

- README.md
Added [NonSteamLaunchers-On-Steam-Deck] under #Launcher
Added [Install Chiaki] under #Guide
Added [Activate SFTP] under #Guide
> Adding chiaki, activate sftp and non steam launchers

- README.md
Compile all the informations written below to send a legitimate pull request to the repository!
- Closes #9;
- Closes #4;
- Closes #3;
I've added the entries into the list.
> feat: add elements to the list

- README.md
- Closes /;
I've added podcasts and removed content creators.
> feat: add podcasts

- README.md
- Closes /;
Adds a guide for Xbox Cloud Gaming.
> feat: add xbox cloud gaming guide

- README.md
Compile all the informations written below to send a legitimate pull request to the repository!
- Closes #;
- ...
Write your solution here...
> Added PSVita emulator (Vita3K)

- README.md
- Closes /;
Adds various emulators.
> feat: add various emulators

- README.md
- Closes /;
Adds discord overlay.
> feat: add discord overlay

- README.md
- Closes /;
Adds various guides.
> feat: add various guides

- i18n/README.it-IT.md
- pirasafe/README.it-IT.md
- pirasafe/README.md
- Closes #7;
- Refers #2;
Adds it i18n and pirasafe.
> feat: add i18n it and pirasafe

- partnerships/STEAM_DECK_ITALIA.md
- Closes /;
Adds first partnership list.
> feat(partnerships): add steam deck italia

- partnerships/STEAM_DECK_ITALIA.md
- Closes /;
- Adds new sections;
- Adds various new products;
- Various corrections.
> feat(partnerships): add various categories and products to STEAM_DECK_ITALIA.md

- .github/workflows/main.yml
- Closes #23;
I've added an action to run automatically awesome-lint against main branch.
> ci: add awesome lint automation

- .github/workflows/main.yml
> ci: change names in main.yml

- LICENSE
> chore: add an extended version of CC0 license

- .github/FUNDING.yml
> chore: remove linktree from funding

- README.md
- Closes #30;
Adds `SteamOS Btrfs` to `Software` section.
> feat: add steamos btrfs

- .github/workflows/linker.yml
Adds link checker automated workflow for increasing link consistency and quality over time.
> feat(ci): add linker.yml

- .github/workflows/linter.yml
Adds linter also on pushes toward main branch.
> feat(ci): add linter also on push

- .github/workflows/interaction.yml
Renames interaction-checker job name to interact.
> refactor(ci): change interaction-checker job name

- README.md
No issue, I've added some communities and one blog to the list
> feat: add communities and blog

- README.md
Adds Steam Deck accessories and one useful website for games compatibility.
> feat: add accessories

- README.md
- Added steam deck refurbished
- Best accessories recommended by XDA
- Added two interesting software for third-party tools and graphical boot manager
- Moved deck verified from utility to general website
- Added r/WindowsOnDeck subreddit
> feat: add various links

- README.md
- Closes #42;
Adds MagicPods plugin.
> feat: add magicpods plugin

- README.md
- Closes #44;
Adds `Greenlight` to remote category.
> feat: add greenlight to remote

- README.md
- Closes #;
- ...
Adds `Steam Deck Web App Generator` website.
> feat: 🎸 add steam deck web app generator

- README.md
- Closes #;
- ...
Adds `shadPS4` emulator.
Website: https://shadps4.net/
Rep: https://github.com/shadps4-emu/shadPS4
> feat: add shadPS4
